CREATE DEFINER=`root`@`localhost` FUNCTION `GET_FISCAL_QUARTER`(
calendar_date DATE 

) RETURNS varchar(2) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE FISCAL_QUARTER varchar(2);
DECLARE QUARTER_MONTH int;
SET QUARTER_MONTH = MONTH(CALENDAR_DATE);
SET FISCAL_QUARTER = 
CASE 
	WHEN QUARTER_MONTH BETWEEN 9 AND 11 THEN"Q1"
    WHEN QUARTER_MONTH in (12, 1,2) THEN "Q2"
    WHEN QUARTER_MONTH BETWEEN 3 AND 5 THEN "Q3"
    else "Q4"
END;
RETURN FISCAL_QUARTER;
END