CREATE DEFINER=`root`@`localhost` PROCEDURE `CUSTOMER_SALES_YEARLY`(
IN_CUSTOMER_CODE TEXT
)
BEGIN
	SELECT
	GET_FISCAL_YEAR(DATE) AS FISCAL_YEAR,
	SUM(G.GROSS_PRICE*S.SOLD_QUANTITY) AS TOTAL_GROSS_PRICE
	FROM FACT_SALES_MONTHLY S
	JOIN FACT_GROSS_PRICE G
	ON S.PRODUCT_CODE = G.PRODUCT_CODE AND G.FISCAL_YEAR = GET_FISCAL_YEAR(S.DATE)

		WHERE find_in_set(S.CUSTOMER_CODE, IN_CUSTOMER_CODE)>0
		GROUP BY GET_FISCAL_YEAR(DATE)
		ORDER BY FISCAL_YEAR ASC;
END