CREATE DEFINER=`root`@`localhost` PROCEDURE `CUSTOMER_SALES_MONTHLY`(
C_CODE int

)
BEGIN
	SELECT
	S.DATE,
	SUM(G.GROSS_PRICE*S.SOLD_QUANTITY) AS TOTAL_GROSS_PRICE
	FROM fact_sales_monthly S
	JOIN FACT_GROSS_PRICE G
	ON G.PRODUCT_CODE = S.PRODUCT_CODE AND G.FISCAL_YEAR= GET_FISCAL_YEAR(S.DATE)
	WHERE CUSTOMER_CODE =C_CODE
	GROUP BY S.DATE
	ORDER BY DATE ASC;
END